### PR TITLE
T/201

### LINKED ISSUE #201: Quick Fix for imgShouldNotHaveTitle
There is a problem when fixing a title for the image.

Current quick fix uses `AttributeRename` QF and blindly renames actual `title` to `alt` which is wrong because we might already have better/correct title in the place.

Actually this was a case in a particular use case:

1. Consider a sport car image that has no `alt` and `title` set to value "placeholder".
1. AC reports an issue that the image has no alt.
1. User sets the alt value to "sport car" and clicks the quick fix button.
1. AC reports an issue that the title attr should not be used, and suggests new alt value, setting it to "placeholder".

Result:

User is confused and might override the alt text that he has just set.

### PR DESCRIPTION
**Pull request by Tade0**
Fixes #201.

### CODE REVIEW

File: quickfix/AttributeRenameDefault.js [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+ * For licensing, see LICENSE.md or http://ckeditor.com/license
+ */
+
+( function() {
+	'use strict'
+
+	CKEDITOR.plugins.a11ychecker.quickFixes.get( {
+		name: 'AttributeRename',
+		callback: function( QuickFix ) {
+			function AttributeRenameDefault(issue) {
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Codestyle issue, no spaces between parenthesis. Do you have linting task hooked to git?

File: quickfix/AttributeRenameDefault.js [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+ * @license Copyright (c) 2014-2016, CKSource - Frederico Knabben. All rights reserved.
+ * For licensing, see LICENSE.md or http://ckeditor.com/license
+ */
+
+( function() {
+	'use strict'
+
+	CKEDITOR.plugins.a11ychecker.quickFixes.get( {
+		name: 'AttributeRename',
+		callback: function( QuickFix ) {
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Please fetched type name as a variable name, so that `QuickFix` becomes `AttributeRename`.

File: quickfix/AttributeRenameDefault.js [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+				QuickFix.call(this, issue);
+			}
+
+			AttributeRenameDefault.prototype = new QuickFix();
+
+			AttributeRenameDefault.prototype.constructor = AttributeRenameDefault;
+
+			CKEDITOR.tools.extend( AttributeRenameDefault.prototype, {
+				display: function( form ) {
+					var proposedValue = this.issue.element.getAttribute( this.attributeTargetName ) ||
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Extracting `this.issue.element` would increase the readability a little bit.

File: quickfix/AttributeRenameDefault.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+ */
+
+( function() {
+	'use strict'
+
+	CKEDITOR.plugins.a11ychecker.quickFixes.get( {
+		name: 'AttributeRename',
+		callback: function( QuickFix ) {
+			function AttributeRenameDefault(issue) {
+				QuickFix.call(this, issue);
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Again, no spaces.

File: quickfix/AttributeRenameDefault.js [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+			}
+
+			AttributeRenameDefault.prototype = new QuickFix();
+
+			AttributeRenameDefault.prototype.constructor = AttributeRenameDefault;
+
+			CKEDITOR.tools.extend( AttributeRenameDefault.prototype, {
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: No need to use `CKEDITOR.tools.extend` on prototype in this case, so far there was no need for it so we're sticking to vanilla js.

Actually I think that instead of overriding `display` method, you could do a minor refactoring in `AttributeRename.display` - you can just extract the value obtaining into a method. Then override this method in `AttributeRenameDefault` type.

File: quickfix/AttributeRenameDefault.js (hunk 1 above)
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Also we need to provide some API docs, what's the purpose of this type? What was the reason for it to be created?

File: quickfix/AttributeRenameDefault.js [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+			 */
+			function AttributeRenameDefault( issue ) {
+				AttributeRename.call( this, issue );
+			}
+
+			AttributeRenameDefault.prototype = new AttributeRename();
+
+			AttributeRenameDefault.prototype.constructor = AttributeRenameDefault;
+
+			CKEDITOR.tools.extend( AttributeRenameDefault.prototype, {
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: No need to use `CKEDITOR.tools.extend` here.

File: quickfix/AttributeRenameDefault.js [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+				getProposedValue: function() {
+					var element = this.issue.element;
+					return	element.getAttribute( this.attributeTargetName ) ||
```
Comment (mlewand) [inline quickfix/AttributeRenameDefault.js]: Code style: double space here, should be just one.

**Comment by mlewand** [comment]
Still I can see two code style issues. I've fixed the tests here are my notes:

* Actually there is no reason to test `AttributeRenameDefault.display` as it was not a subject of change. Instead those should test 
* I've also updated the tests for the base implementation `AttributeRename.display` to better test changes introduced recently.

Let's get these two remaining problems fixed and we're good to go.

**Comment by Tade0** [comment]
Fixed and rebased.
